# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
- job: BuildAndPush
  displayName: 'Build and Push Docker Image'
  steps:
  - task: Docker@2
    inputs:
      containerRegistry: 'acrServiceConnection'
      repository: 'newreg'
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'